name: build-rockchip

permissions: write-all

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
   - cron: 0 20 * * 2

env:
  FREE_DISK_SH: scripts/free_disk_space.sh
  ENV_SH: scripts/environment.sh
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  PLATFORM_FILE: configs/rockchip-L.txt
  CONFIG_FILE: configs/packages.txt
  CONFIG_5G: configs/packages-5G.txt
  SETTINGS_SH: scripts/init-settings.sh
  PACKAGES_SH: scripts/packages.sh
  INSTALL5G_SH: scripts/install-5G.sh
  CLASH_CORE_SH: scripts/preset-clash-core-arm64-L.sh
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: false
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: æ£€æŸ¥ä»£ç 
      uses: actions/checkout@main

    - name: åˆå§‹åŒ–ç¯å¢ƒ & é‡Šæ”¾ç£ç›˜ç©ºé—´
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        chmod +x $FREE_DISK_SH && $FREE_DISK_SH
        sudo -E apt-get -qq update -y
        sudo -E apt-get -qq full-upgrade -y
        chmod +x $ENV_SH && $ENV_SH
        # åˆ é™¤å¤§ç›®å½•
        sudo rm -rf /etc/apt/sources.list.d/*
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /opt/ghc
        sudo rm -rf /usr/local/share/boost
        sudo rm -rf /var/lib/apt/lists/*
        sudo apt-get clean
        # æ¸…ç† Docker
        docker system prune -af --volumes
        # åˆ é™¤ GitHub Actions å·¥å…·ç¼“å­˜
        sudo rm -rf /opt/hostedtoolcache
        # æ—¶åŒº
        sudo timedatectl set-timezone "$TZ"
        # åˆ›å»ºå·¥ä½œç›®å½•
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir

    - name: æ£€æŸ¥ç£ç›˜ç©ºé—´
      run: df -hT

    - name: å…‹éš†æºç 
      working-directory: /workdir
      run: |
        git clone $REPO_URL --depth 1 -b $REPO_BRANCH openwrt
        ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt

    - name: å¼€å¯ç¼“å­˜ï¼ˆä»…ç¼“å­˜ dl ç›®å½•ï¼‰
      uses: klever1988/cachewrtbuild@main
      with:
        ccache: 'false'
        mixkey: 'rockchip'
        prefix: ${{ github.workspace }}/openwrt
        cachepath: dl

    - name: å®‰è£… feeds
      run: |
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: å¯¼å…¥è¡¥ä¸å’Œé…ç½® & æ‰§è¡Œè„šæœ¬
      run: |
        [ -d files ] && mv files openwrt/files || echo "files not found"
        [ -f $CONFIG_5G ] && cat $CONFIG_5G >> openwrt/.config
        [ -f $PLATFORM_FILE ] && cat $PLATFORM_FILE >> openwrt/.config
        [ -f $CONFIG_FILE ] && cat $CONFIG_FILE >> openwrt/.config
        cd openwrt
        rm target/linux/rockchip/patches-*/991-arm64-dts-rockchip-add-more-cpu-operating-points-for.patch || true
        chmod +x $GITHUB_WORKSPACE/$INSTALL5G_SH && $GITHUB_WORKSPACE/$INSTALL5G_SH
        chmod +x $GITHUB_WORKSPACE/$SETTINGS_SH && $GITHUB_WORKSPACE/$SETTINGS_SH
        chmod +x $GITHUB_WORKSPACE/$PACKAGES_SH && $GITHUB_WORKSPACE/$PACKAGES_SH
        chmod +x $GITHUB_WORKSPACE/$CLASH_CORE_SH && $GITHUB_WORKSPACE/$CLASH_CORE_SH

    - name: ä¸‹è½½ä¾èµ–åŒ…
      run: |
        cd openwrt
        make defconfig
        make download -j$(nproc) V=s
        # æ£€æŸ¥ä¸‹è½½æƒ…å†µ
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: æ£€æŸ¥ç£ç›˜ç©ºé—´ï¼ˆä¸‹è½½åï¼‰
      run: df -hT

    - name: ç¼–è¯‘å·¥å…·é“¾
      id: mtools
      run: |
        cd openwrt
        make tools/compile -j1 V=s
        make toolchain/compile -j1 V=s
        echo "status=success" >> $GITHUB_OUTPUT

    - name: æ£€æŸ¥ç£ç›˜ç©ºé—´ï¼ˆå·¥å…·é“¾åï¼‰
      run: df -hT

    - name: æ¸…ç†å·¥å…·é“¾ä¸­é—´æ–‡ä»¶
      if: steps.mtools.outputs.status == 'success'
      run: |
        cd openwrt
        rm -rf build_dir/toolchain-*

    - name: ç¼–è¯‘å†…æ ¸
      id: mkernel
      if: steps.mtools.outputs.status == 'success'
      run: |
        cd openwrt
        make target/linux/compile -j1 V=s
        echo "status=success" >> $GITHUB_OUTPUT

    - name: æ£€æŸ¥ç£ç›˜ç©ºé—´ï¼ˆå†…æ ¸åï¼‰
      run: df -hT

    - name: ç¼–è¯‘æ’ä»¶
      id: mpackage
      if: steps.mkernel.outputs.status == 'success'
      run: |
        cd openwrt
        make package/compile -j1 V=s
        make package/index
        make package/install -j1 V=s
        echo "status=success" >> $GITHUB_OUTPUT

    - name: æ£€æŸ¥ç£ç›˜ç©ºé—´ï¼ˆæ’ä»¶åï¼‰
      run: df -hT

    - name: æ¸…ç†æ’ä»¶ç¼–è¯‘æ–‡ä»¶
      if: steps.mpackage.outputs.status == 'success'
      run: |
        cd openwrt
        rm -rf build_dir/target-*/host

    - name: ç¼–è¯‘å›ºä»¶
      id: compile
      if: steps.mpackage.outputs.status == 'success'
      run: |
        cd openwrt
        make target/install -j1 V=s
        make json_overview_image_info
        make checksum
        echo "status=success" >> $GITHUB_OUTPUT

    - name: æ£€æŸ¥ç£ç›˜ç©ºé—´ï¼ˆå›ºä»¶åï¼‰
      run: df -hT

    - name: æ•´ç†æ–‡ä»¶
      id: organize
      if: steps.compile.outputs.status == 'success'
      run: |
        cd openwrt/bin/targets/*/*
        rm -rf *.bin *.buildinfo *.json *.manifest packages
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
        echo "status=success" >> $GITHUB_OUTPUT

    - name: å›ºä»¶é‡å‘½å
      if: steps.organize.outputs.status == 'success'
      shell: bash
      run: |
        cd openwrt/bin/targets/*/*
        for file in *rockchip-armv8-*.gz; do
          new_name=$(echo "$file" | sed 's/rockchip-armv8-//')
          mv -v "$file" "$new_name"
        done
      
    - name: ä¸Šä¼ å›ºä»¶ç›®å½•
      uses: actions/upload-artifact@main
      if: env.UPLOAD_FIRMWARE == 'true' && steps.organize.outputs.status == 'success' && !cancelled()
      with:
        name: OpenWrt_firmware${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
        path: ${{ env.FIRMWARE }}

    - name: ç”Ÿæˆå‘å¸ƒæ ‡ç­¾
      id: tag
      if: env.UPLOAD_RELEASE == 'true' && steps.compile.outputs.status == 'success' && !cancelled()
      run: |
        echo -e "ğŸ‰ rockchipå¹³å°\nâœ… ä¸»çº¿æºç \nğŸƒ å¦‚å‡ºç°ä¸ç¨³å®šå¯å°è¯•cpué™é¢‘\nâ—ï¸ ipåœ°å€ : 192.168.8.1" >> release.txt
        echo "release_tag=$(date +"%Y.%m.%d_Rockchip")" >> $GITHUB_OUTPUT
        echo "status=success" >> $GITHUB_OUTPUT

    - name: ä¸Šä¼ å›ºä»¶åˆ°å‘å¸ƒ
      uses: softprops/action-gh-release@v2.0.4
      if: steps.tag.outputs.status == 'success' && !cancelled()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        body_path: release.txt
        files: ${{ env.FIRMWARE }}/*

    - name: åˆ é™¤æ—§å‘å¸ƒ
      if: steps.compile.outputs.status == 'success' && env.UPLOAD_RELEASE == 'true'
      uses: dev-drprasad/delete-older-releases@v0.3.3
      with:
        keep_latest: 15
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: åˆ é™¤æ—§ workflow
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repository: ${{ github.repository }}
        retain_days: 1
        keep_minimum_runs: 3
